# Generated by Django 4.2.3 on 2023-08-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_tag_projects_vote_ratio_projects_vote_total_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='featured_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
