# Generated by Django 4.2.3 on 2023-08-21 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_projects_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'ordering': ['created']},
        ),
    ]
