# Generated by Django 4.2.3 on 2023-08-21 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_review_owner_alter_review_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'ordering': ['-vote_ratio', '-vote_total']},
        ),
    ]
